### PR TITLE
Updating bugwarrior to 1.5.1

### PR DESCRIPTION
**Pull request by Tzrlk**
I've updated this manually because I don't have a python dev environment available, but the auto-build should pick up whether this will actually work.

### CODE REVIEW

**Comment by Tzrlk** [comment]
Ah, apparently you don't have pull-request builds enabled. There goes that plan.

Reckon you could incorporate the gist of this change, @coddingtonbear ?
It'd be great to use the newer templating features of bugwarrior.

**Comment by coddingtonbear** [comment]
I'm really sorry to say this, but the auto build will not help out with identifying whether this upgrade was successful -- the integration with Bugwarrior is essentially untested.  I'll try to find time some time to have a look into whether [inthe.am's bugwarrior adapter](https://github.com/coddingtonbear/inthe.am/blob/development/inthe_am/taskmanager/bugwarrior_adapter.py) is sufficient for the new version of Bugwarrior, but I'm afraid it might be quite a while before I'm able to find such a window.

If you were to run Inthe.AM locally, though, you might be able to perform such manual tests on your own, though.

**Comment by coddingtonbear** [comment]
I'm afraid I'm going to be deprecating integrated Bugwarrior support in the next few days!  Thanks for trying to update, though!

**Comment by Tzrlk** [comment]
Ah well. I ended up running bugwarrior on a local machine and syncing the issues anyway.

**Pull request closed without merging**
